# Generated by Django 4.2 on 2023-04-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todolist_delete_task'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todolist',
            table='todo_list',
        ),
    ]
